In [1]:
import numpy as np

## Vector vector multiplication

In [2]:
def vector_vector_multiplication(u, v):
    assert u.shape[0] == v.shape[0]
     
    n = u.shape[0]
     
    result = 0.0
     
    for i in range(n):
        result = result + u[i] * v[i]
     
    return result


In [3]:
u = np.array([2, 4, 5, 6])
v = np.array([1, 0, 0, 2])
vector_vector_multiplication(u, v)


14.0

In [4]:
u.dot(v)


14

## Matrix vector multiplication

In [5]:
def matrix_vector_multiplication(U, v):
    assert U.shape[1] == v.shape[0]
     
    num_rows = U.shape[0]
     
    result = np.zeros(num_rows)
     
    for i in range(num_rows):
        result[i] = vector_vector_multiplication(U[i], v)
     
    return result

In [6]:
U = np.array([
    [2, 4, 5, 6],
    [1, 2, 1, 2],
    [3, 1, 2, 1]
])
 
v = np.array([1, 0, 0, 2])
 
matrix_vector_multiplication(U, v)

array([14.,  5.,  5.])

In [7]:
U.dot(v)

array([14,  5,  5])

## Matrix matrix multiplication

In [8]:
def matrix_matrix_multiplication(U, V):
    assert U.shape[1] == V.shape[0]
     
    num_rows = U.shape[0]
    num_columns = V.shape[1]
     
    result = np.zeros((num_rows, num_columns))
     
    for i in range(num_columns):
        vi = V[:, i]
        Uvi = matrix_vector_multiplication(U, vi)
        result[:, i] = Uvi
     
    return result

In [9]:
U = np.array([
    [2, 4, 5, 6],
    [1, 2, 1, 2],
    [3, 1, 2, 1]
])
 
V = np.array([
    [1, 1, 2],
    [0, 0.5, 1],
    [0, 3, 1],
    [2, 1, 0]
])
 
matrix_matrix_multiplication(U, V)

array([[14. , 25. , 13. ],
       [ 5. ,  7. ,  5. ],
       [ 5. , 10.5,  9. ]])

In [10]:
U.dot(V)

array([[14. , 25. , 13. ],
       [ 5. ,  7. ,  5. ],
       [ 5. , 10.5,  9. ]])

## Identity matrix

In [13]:
I = np.eye(3)

In [14]:
V = np.array([
    [1, 1, 2],
    [0, 0.5, 1],
    [0, 3, 1],
    [2, 1, 0]
])
 
V.dot(I)

array([[1. , 1. , 2. ],
       [0. , 0.5, 1. ],
       [0. , 3. , 1. ],
       [2. , 1. , 0. ]])

In [15]:
V.dot(I) == V

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

## Inverse matrix

In [16]:
V = np.array([
    [1, 1, 2],
    [0, 0.5, 1],
    [0, 3, 1]
])

V_inv = np.linalg.inv(V)
V_inv

array([[ 1. , -2. ,  0. ],
       [ 0. , -0.4,  0.4],
       [ 0. ,  1.2, -0.2]])

## Eigenvalues and Eigenvectors

- An eigenvector of a matrix U is a non-zero vector that, when multiplied by U, yields a scalar multiple of itself. In other words, the eigenvector remains in the same direction, although its magnitude may change.
- Mathematically, for a square matrix U and its corresponding eigenvector v, the equation for eigenvalues and eigenvectors is given by:

U * v = λ * v